# Generated by Django 6.0.8 on 2026-08-16 16:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stories', '0001_initial'),
        ('writers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StorySeries',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('UNPUBLISHED', 'Unpublished'), ('COMPLETED', 'Completed'), ('ARCHIVED', 'Archived')], db_index=True, default='DRAFT', max_length=20)),
                ('total_stories', models.PositiveIntegerField(default=0)),
                ('completed_stories', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_series', to=settings.AUTH_USER_MODEL)),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='writers.writerprofile')),
            ],
            options={
                'db_table': 'story_series',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StorySeriesItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence_number', models.PositiveIntegerField()),
                ('item_status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('PUBLISHED', 'Published'), ('COMPLETED', 'Completed')], default='UPCOMING', max_length=20)),
                ('expected_publish_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='series.storyseries')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_items', to='stories.story')),
            ],
            options={
                'db_table': 'story_series_items',
                'ordering': ['sequence_number'],
                'unique_together': {('series', 'sequence_number'), ('series', 'story')},
            },
        ),
    ]
