# Generated by Django 6.0.8 on 2026-08-29 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_consent_fields'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='users_email_4b85f2_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_role_0ace22_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_is_acti_847b48_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_created_6541e9_idx',
        ),
    ]
