# Generated by Django 6.0.8 on 2026-08-16 16:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section_key', models.CharField(choices=[('HERO_BANNER', 'Hero Banner'), ('FEATURED_STORY', 'Featured Story'), ('LATEST_STORIES', 'Latest Stories'), ('TRENDING_STORIES', 'Trending Stories'), ('FEATURED_BLOGS', 'Featured Blogs'), ('FEATURED_WRITERS', 'Featured Writers'), ('LATEST_VIDEOS', 'Latest Videos'), ('CATEGORIES', 'Categories'), ('NEWSLETTER', 'Newsletter')], db_index=True, max_length=50, unique=True)),
                ('title', models.CharField(blank=True, help_text='Display title override', max_length=255)),
                ('is_enabled', models.BooleanField(db_index=True, default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('config', models.JSONField(blank=True, default=dict, help_text="Per-section layout config e.g. {'count': 6, 'layout': 'grid'}")),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'homepage_sections',
                'ordering': ['display_order'],
            },
        ),
    ]
