# Generated by Django 6.0.8 on 2026-08-20 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagesection',
            name='section_key',
            field=models.CharField(choices=[('HERO_BANNER', 'Hero Banner'), ('FEATURED_STORY', 'Featured Story'), ('LATEST_STORIES', 'Latest Stories'), ('TRENDING_STORIES', 'Trending Stories'), ('FEATURED_BLOGS', 'Featured Blogs'), ('FEATURED_WRITERS', 'Featured Writers'), ('LATEST_VIDEOS', 'Latest Videos'), ('CATEGORIES', 'Categories'), ('NEWSLETTER', 'Newsletter'), ('ANNOUNCEMENT', 'Announcement Bar'), ('FOOTER', 'Footer Settings'), ('CONTACT', 'Contact Settings'), ('STORY_SLOTS', 'Story Section Slots')], db_index=True, max_length=50, unique=True),
        ),
    ]
