# Generated by Django 6.0.8 on 2026-08-16 16:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WriterProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('bio', models.TextField(blank=True)),
                ('profile_photo', models.URLField(blank=True)),
                ('website_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('x_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('is_verified', models.BooleanField(db_index=True, default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('total_stories', models.PositiveIntegerField(default=0)),
                ('total_published_stories', models.PositiveIntegerField(default=0)),
                ('total_reads', models.BigIntegerField(default=0)),
                ('total_likes', models.BigIntegerField(default=0)),
                ('total_shares', models.BigIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='writer_profile', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_writers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'writer_profiles',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['slug'], name='writer_prof_slug_a5d932_idx'), models.Index(fields=['is_verified'], name='writer_prof_is_veri_64c680_idx'), models.Index(fields=['is_active'], name='writer_prof_is_acti_4e753b_idx')],
            },
        ),
    ]
