# Generated by Django on 2026-09-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writers', '0002_writerprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='writerprofile',
            name='location',
            field=models.CharField(blank=True, default='India', max_length=255),
        ),
        migrations.AddField(
            model_name='writerprofile',
            name='author_title',
            field=models.CharField(blank=True, default='tossatale author', max_length=255),
        ),
        migrations.AddField(
            model_name='writerprofile',
            name='tagline',
            field=models.CharField(blank=True, default='Storyteller', max_length=255),
        ),
    ]
