# Generated by Django on 2026-09-26

import uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('writers', '0003_writerprofile_location_author_title_tagline'),
    ]

    operations = [
        migrations.CreateModel(
            name='WriterSupport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('ip_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='writer_supports', to=settings.AUTH_USER_MODEL)),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supports', to='writers.writerprofile')),
            ],
            options={
                'db_table': 'writer_supports',
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['writer', 'created_at'], name='writer_supp_writer__3b4b8a_idx'),
                    models.Index(fields=['user', 'writer', 'created_at'], name='writer_supp_user_id_0f7ef8_idx'),
                    models.Index(fields=['ip_hash', 'writer', 'created_at'], name='writer_supp_ip_hash_cf469b_idx'),
                ],
            },
        ),
    ]
