# Generated by Django 6.0.8 on 2026-10-01 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writers', '0004_writersupport'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='writersupport',
            new_name='writer_supp_writer__7a9299_idx',
            old_name='writer_supp_writer__3b4b8a_idx',
        ),
        migrations.RenameIndex(
            model_name='writersupport',
            new_name='writer_supp_user_id_10fb59_idx',
            old_name='writer_supp_user_id_0f7ef8_idx',
        ),
        migrations.RenameIndex(
            model_name='writersupport',
            new_name='writer_supp_ip_hash_9083f5_idx',
            old_name='writer_supp_ip_hash_cf469b_idx',
        ),
        migrations.RemoveField(
            model_name='writerprofile',
            name='profile_photo',
        ),
        migrations.AlterField(
            model_name='writerprofile',
            name='author_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='writerprofile',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='writerprofile',
            name='tagline',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
