# Generated by Django 6.0.8 on 2026-08-16 16:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('writers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('subtitle', models.CharField(blank=True, max_length=500, null=True)),
                ('content', models.TextField(help_text='Rich text prose content (text-only for writers per §2)')),
                ('plain_text_content', models.TextField(blank=True, help_text='Plain text content used for search indexing and reading time calculation')),
                ('seo_title', models.CharField(blank=True, max_length=70)),
                ('seo_description', models.CharField(blank=True, max_length=160)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_REVIEW', 'Pending Review'), ('APPROVED', 'Approved'), ('PUBLISHED', 'Published'), ('REJECTED', 'Rejected'), ('ARCHIVED', 'Archived'), ('SCHEDULED', 'Scheduled')], db_index=True, default='DRAFT', max_length=20)),
                ('moderation_status', models.CharField(choices=[('NOT_REVIEWED', 'Not Reviewed'), ('PASSED', 'Passed'), ('FLAGGED', 'Flagged'), ('BLOCKED', 'Blocked')], default='NOT_REVIEWED', max_length=20)),
                ('rejection_feedback', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('scheduled_publish_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('allow_comments', models.BooleanField(default=True)),
                ('estimated_reading_time', models.PositiveIntegerField(default=0, help_text='Reading time in minutes')),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('views_count', models.BigIntegerField(default=0)),
                ('likes_count', models.BigIntegerField(default=0)),
                ('shares_count', models.BigIntegerField(default=0)),
                ('bookmarks_count', models.BigIntegerField(default=0)),
                ('trending_score', models.DecimalField(db_index=True, decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stories', to='categories.category')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_stories', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_stories', to=settings.AUTH_USER_MODEL)),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='writers.writerprofile')),
            ],
            options={
                'db_table': 'stories',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoryReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CHANGES_REQUESTED', 'Changes Requested')], max_length=20)),
                ('feedback', models.TextField(blank=True)),
                ('internal_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conducted_reviews', to=settings.AUTH_USER_MODEL)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='stories.story')),
            ],
            options={
                'db_table': 'story_reviews',
                'ordering': ['-reviewed_at'],
            },
        ),
        migrations.CreateModel(
            name='StoryRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=500, null=True)),
                ('content', models.TextField()),
                ('seo_title', models.CharField(blank=True, max_length=70)),
                ('seo_description', models.CharField(blank=True, max_length=160)),
                ('change_summary', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.category')),
                ('edited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='stories.story')),
            ],
            options={
                'db_table': 'story_revisions',
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='StoryTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_tags', to='stories.story')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_stories', to='categories.tag')),
            ],
            options={
                'db_table': 'story_tags',
            },
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['slug'], name='stories_slug_19fa93_idx'),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['status'], name='stories_status_a9167d_idx'),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['published_at'], name='stories_publish_4c076e_idx'),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['writer'], name='stories_writer__5abc19_idx'),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['category'], name='stories_categor_56d678_idx'),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['is_featured'], name='stories_is_feat_f12466_idx'),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['trending_score'], name='stories_trendin_c006e2_idx'),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['status', 'published_at'], name='stories_status_4ce181_idx'),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['writer', 'status'], name='stories_writer__384fe8_idx'),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['category', 'status'], name='stories_categor_56f0c8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='storyrevision',
            unique_together={('story', 'version_number')},
        ),
        migrations.AlterUniqueTogether(
            name='storytag',
            unique_together={('story', 'tag')},
        ),
    ]
