# Generated by Django 6.0.8 on 2026-08-20 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='unauthenticated_like_attempts',
            field=models.BigIntegerField(default=0),
        ),
    ]
