# Generated by Django on 2026-09-16

import uuid
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_story_unauthenticated_like_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='is_multi_chapter',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether story is composed of multiple sequential chapters'),
        ),
        migrations.CreateModel(
            name='StoryChapter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(db_index=True, default=1)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField(blank=True, help_text='Rich text prose content of the chapter')),
                ('plain_text_content', models.TextField(blank=True)),
                ('estimated_reading_time', models.PositiveIntegerField(default=0, help_text='Reading time in minutes')),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='stories.story')),
            ],
            options={
                'db_table': 'story_chapters',
                'ordering': ['order'],
                'unique_together': {('story', 'order')},
            },
        ),
    ]
