# Generated by Django on 2026-09-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_story_chapters'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='series_status',
            field=models.CharField(
                choices=[('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed')],
                db_index=True,
                default='ONGOING',
                help_text='Whether this multi-chapter series is actively ongoing or completed',
                max_length=20,
            ),
        ),
    ]
