# Generated by Django on 2026-09-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0004_story_series_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='storychapter',
            name='status',
            field=models.CharField(
                choices=[
                    ('DRAFT', 'Draft'),
                    ('PENDING_REVIEW', 'Pending Review'),
                    ('APPROVED', 'Approved'),
                    ('PUBLISHED', 'Published'),
                    ('REJECTED', 'Rejected'),
                    ('ARCHIVED', 'Archived'),
                    ('SCHEDULED', 'Scheduled'),
                ],
                db_index=True,
                default='DRAFT',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='storychapter',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storychapter',
            name='rejection_feedback',
            field=models.TextField(blank=True),
        ),
    ]
