# Generated by Django on 2026-09-17

from django.db import migrations


def normalize_all_chapter_orders(apps, schema_editor):
    Story = apps.get_model('stories', 'Story')
    StoryChapter = apps.get_model('stories', 'StoryChapter')

    for story in Story.objects.all():
        chapters = list(StoryChapter.objects.filter(story=story).order_by('order', 'created_at'))
        if not chapters:
            continue
        
        # Step 1: Temporarily assign high orders to prevent unique constraint collisions
        for i, ch in enumerate(chapters):
            StoryChapter.objects.filter(id=ch.id).update(order=10000 + i)

        # Step 2: Re-assign strictly sequential 1-indexed order (1, 2, 3...)
        for i, ch in enumerate(chapters):
            StoryChapter.objects.filter(id=ch.id).update(order=i + 1)


def reverse_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0005_story_chapter_status'),
    ]

    operations = [
        migrations.RunPython(normalize_all_chapter_orders, reverse_noop),
    ]
