# Generated by Django 6.0.8 on 2026-08-16 16:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('FACEBOOK', 'Facebook'), ('X', 'X (Twitter)'), ('LINKEDIN', 'LinkedIn'), ('COPY_LINK', 'Copy Link'), ('EMAIL', 'Email'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('session_id', models.CharField(blank=True, max_length=255)),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='stories.story')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='story_shares', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'story_shares',
                'ordering': ['-shared_at'],
            },
        ),
        migrations.CreateModel(
            name='RecentlyRead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_read_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('reading_progress', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('completed', models.BooleanField(default=False)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_history', to='stories.story')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recently_read', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recently_read',
                'ordering': ['-last_read_at'],
                'indexes': [models.Index(fields=['user', 'last_read_at'], name='recently_re_user_id_01f9e1_idx')],
                'unique_together': {('user', 'story')},
            },
        ),
        migrations.CreateModel(
            name='StoryBookmark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_by', to='stories.story')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'story_bookmarks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'story'], name='story_bookm_user_id_32d363_idx')],
                'unique_together': {('user', 'story')},
            },
        ),
        migrations.CreateModel(
            name='StoryLike',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='stories.story')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_stories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'story_likes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'story'], name='story_likes_user_id_d0c93b_idx')],
                'unique_together': {('user', 'story')},
            },
        ),
        migrations.CreateModel(
            name='StoryView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(blank=True, max_length=255)),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('referrer', models.CharField(blank=True, max_length=500)),
                ('traffic_source', models.CharField(blank=True, max_length=100)),
                ('device_type', models.CharField(blank=True, max_length=50)),
                ('browser', models.CharField(blank=True, max_length=50)),
                ('country', models.CharField(blank=True, max_length=10)),
                ('viewed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('reading_duration', models.PositiveIntegerField(default=0, help_text='Reading duration in seconds')),
                ('completion_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('is_unique_view', models.BooleanField(default=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='stories.story')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='story_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'story_views',
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['story', 'viewed_at'], name='story_views_story_i_4e8ebd_idx'), models.Index(fields=['user', 'story'], name='story_views_user_id_4a5f72_idx')],
            },
        ),
    ]
