# Generated by Django 6.0.8 on 2026-08-16 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.IntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('site_name', models.CharField(default='Tossatale', max_length=150)),
                ('tagline', models.CharField(default='Where Stories Live and Breathes', max_length=255)),
                ('logo_url', models.URLField(blank=True)),
                ('favicon_url', models.URLField(blank=True)),
                ('default_from_email', models.EmailField(default='hello@tossatale.com', max_length=254)),
                ('contact_email', models.EmailField(default='support@tossatale.com', max_length=254)),
                ('footer_description', models.TextField(blank=True)),
                ('copyright_text', models.CharField(default='© Tossatale. All rights reserved.', max_length=255)),
                ('social_facebook', models.URLField(blank=True)),
                ('social_instagram', models.URLField(blank=True)),
                ('social_x', models.URLField(blank=True)),
                ('social_linkedin', models.URLField(blank=True)),
                ('social_youtube', models.URLField(blank=True)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('maintenance_message', models.TextField(default="Tossatale is currently undergo scheduled maintenance. We'll be back shortly.")),
                ('analytics_google_id', models.CharField(blank=True, max_length=50)),
                ('analytics_meta_pixel', models.CharField(blank=True, max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'site_settings',
            },
        ),
    ]
