# Generated by Django 6.0.8 on 2026-08-29 07:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_config', '0003_faqitem_basemodel'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            ALTER TABLE "faq_items" DROP CONSTRAINT IF EXISTS faq_items_pkey CASCADE;
            ALTER TABLE "faq_items" DROP COLUMN IF EXISTS "id";
            ALTER TABLE "faq_items" ADD COLUMN "id" uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY;
            """,
            reverse_sql="""
            ALTER TABLE "faq_items" DROP CONSTRAINT IF EXISTS faq_items_pkey CASCADE;
            ALTER TABLE "faq_items" DROP COLUMN IF EXISTS "id";
            ALTER TABLE "faq_items" ADD COLUMN "id" bigserial PRIMARY KEY;
            """,
            state_operations=[
                migrations.AlterField(
                    model_name='faqitem',
                    name='id',
                    field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
            ]
        ),
    ]

