# Generated by Django 6.0.8 on 2026-10-01 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_config', '0004_alter_faqitem_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='maintenance_message',
            field=models.TextField(default='We are currently making a few improvements behind the scenes to make your experience better. Please check back soon.'),
        ),
    ]
