# Generated by Django 6.0.8 on 2026-08-16 16:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('youtube_url', models.URLField(help_text='Full YouTube video URL')),
                ('youtube_video_id', models.CharField(blank=True, max_length=50)),
                ('embed_url', models.URLField(blank=True)),
                ('thumbnail_url', models.URLField(blank=True, help_text='Cloudinary or YouTube default thumbnail URL')),
                ('description', models.TextField(blank=True)),
                ('duration', models.PositiveIntegerField(default=0, help_text='Video duration in seconds')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='categories.category')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_videos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'videos',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
