# Generated by Django 6.0.8 on 2026-08-18 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('videos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='category_name',
            field=models.CharField(blank=True, default='Film', max_length=100),
        ),
        migrations.AddField(
            model_name='video',
            name='cover_image',
            field=models.TextField(blank=True, help_text='Cover poster URL or Base64 data URI'),
        ),
        migrations.AddField(
            model_name='video',
            name='director',
            field=models.CharField(blank=True, default='Tossatale Studio', max_length=255),
        ),
        migrations.AddField(
            model_name='video',
            name='editorial_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='video',
            name='expected_release',
            field=models.CharField(blank=True, default='Coming Soon', max_length=100),
        ),
        migrations.AddField(
            model_name='video',
            name='is_upcoming',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='status',
            field=models.CharField(default='In Production', max_length=100),
        ),
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='categories.category'),
        ),
        migrations.AlterField(
            model_name='video',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_videos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='video',
            name='embed_url',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail_url',
            field=models.TextField(blank=True, help_text='Thumbnail URL or Base64 data URI'),
        ),
        migrations.AlterField(
            model_name='video',
            name='youtube_url',
            field=models.TextField(blank=True, help_text='Full YouTube video URL'),
        ),
    ]
