# Generated by Django 6.0.8 on 2026-08-16 16:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('subtitle', models.CharField(blank=True, max_length=500, null=True)),
                ('content', models.TextField(help_text='Rich HTML content with image support via Cloudinary')),
                ('plain_text_content', models.TextField(blank=True)),
                ('cover_image', models.URLField(blank=True, help_text='Cloudinary cover image URL')),
                ('featured_image', models.URLField(blank=True, help_text='Cloudinary featured image URL')),
                ('seo_title', models.CharField(blank=True, max_length=70)),
                ('seo_description', models.CharField(blank=True, max_length=160)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('SCHEDULED', 'Scheduled'), ('ARCHIVED', 'Archived')], db_index=True, default='DRAFT', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('reading_time', models.PositiveIntegerField(default=0)),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('views_count', models.BigIntegerField(default=0)),
                ('likes_count', models.BigIntegerField(default=0)),
                ('shares_count', models.BigIntegerField(default=0)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('scheduled_publish_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blogs', to='categories.category')),
            ],
            options={
                'db_table': 'blogs',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_tags', to='blogs.blog')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_blogs', to='categories.tag')),
            ],
            options={
                'db_table': 'blog_tags',
                'unique_together': {('blog', 'tag')},
            },
        ),
    ]
