# Generated by Django 6.0.8 on 2026-08-18 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='cover_image',
            field=models.TextField(blank=True, help_text='Cloudinary cover image URL or Base64 data URI'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='featured_image',
            field=models.TextField(blank=True, help_text='Cloudinary featured image URL or Base64 data URI'),
        ),
    ]
