# Generated by Django 6.0.8 on 2026-08-16 16:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stories', '0001_initial'),
        ('writers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPlatformAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True, unique=True)),
                ('total_page_views', models.IntegerField(default=0)),
                ('unique_visitors', models.IntegerField(default=0)),
                ('new_users', models.IntegerField(default=0)),
                ('new_writers', models.IntegerField(default=0)),
                ('total_stories_published', models.IntegerField(default=0)),
                ('total_likes', models.IntegerField(default=0)),
                ('total_shares', models.IntegerField(default=0)),
                ('newsletter_subscriptions', models.IntegerField(default=0)),
                ('top_stories', models.JSONField(blank=True, default=list)),
                ('top_categories', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'daily_platform_analytics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DailyStoryAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('views', models.IntegerField(default=0)),
                ('unique_views', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('unlikes', models.IntegerField(default=0)),
                ('shares', models.IntegerField(default=0)),
                ('bookmarks', models.IntegerField(default=0)),
                ('avg_reading_duration', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('completion_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('country_breakdown', models.JSONField(blank=True, default=dict)),
                ('device_breakdown', models.JSONField(blank=True, default=dict)),
                ('traffic_source_breakdown', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_analytics', to='stories.story')),
            ],
            options={
                'db_table': 'daily_story_analytics',
                'ordering': ['-date'],
                'unique_together': {('story', 'date')},
            },
        ),
        migrations.CreateModel(
            name='DailyWriterAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('total_views', models.IntegerField(default=0)),
                ('total_unique_views', models.IntegerField(default=0)),
                ('total_likes', models.IntegerField(default=0)),
                ('total_shares', models.IntegerField(default=0)),
                ('stories_submitted', models.IntegerField(default=0)),
                ('stories_published', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_analytics', to='writers.writerprofile')),
            ],
            options={
                'db_table': 'daily_writer_analytics',
                'ordering': ['-date'],
                'unique_together': {('writer', 'date')},
            },
        ),
    ]
