# Generated by Django 6.0.8 on 2026-08-16 16:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('stories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('banner_type', models.CharField(choices=[('HERO', 'Hero'), ('PROMOTIONAL', 'Promotional'), ('NEWSLETTER', 'Newsletter'), ('CATEGORY', 'Category')], db_index=True, default='HERO', max_length=20)),
                ('image', models.URLField(help_text='Cloudinary banner image URL')),
                ('mobile_image', models.URLField(blank=True, help_text='Cloudinary mobile banner image URL')),
                ('cta_text', models.CharField(blank=True, help_text='Call to action button text', max_length=100)),
                ('cta_url', models.CharField(blank=True, help_text='Call to action link URL', max_length=500)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_banners', to=settings.AUTH_USER_MODEL)),
                ('linked_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banners', to='categories.category')),
                ('linked_story', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banners', to='stories.story')),
            ],
            options={
                'db_table': 'banners',
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
