# Generated by Django 6.0.8 on 2026-08-29 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_recipie_583549_idx',
            old_name='notificatio_recipie_5cb626_idx',
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('STORY_SUBMITTED', 'Story Submitted'), ('STORY_APPROVED', 'Story Approved'), ('STORY_REJECTED', 'Story Rejected'), ('STORY_FEEDBACK', 'Story Feedback'), ('WRITER_REGISTERED', 'Writer Registered'), ('WRITER_VERIFIED', 'Writer Verified'), ('WRITER_UNVERIFIED', 'Writer Unverified'), ('CONTACT_MESSAGE_RECEIVED', 'Contact Message Received'), ('STORY_PUBLISHED', 'Story Published'), ('SYSTEM_NOTIFICATION', 'System Notification')], max_length=50),
        ),
    ]
